# Generated by Django 3.0.6 on 2020-05-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_news', '0004_auto_20200524_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
